### ISSUE TITLE
add jurisdiction

### ISSUE THREAD

**Issue by luisfelipebr** [digital-guard/stats#1]
https://github.com/digital-guard/stats/blob/c5c4e0939a2a422fbe85c7adc66dfe8e826cd0b9/docs/stats-report.qmd#L113

A quantidade de geoendereços é calculada por doador (legalname). Também seria interessante apresentar os resultados por jurisdiction.

@ppKrauss faço isso agora ou espero os dados consolidados?

**Comment by ppKrauss** [comment]
> faço isso agora ou espero os dados consolidados?

Os dados filtrados são bastante ricos para as estatísticas, pode discriminar também por Jurisdição... O mais simples é aproveitar a mesma tabela e incluir nela a sigla de duas letras do país... Ou apenas concatenar, por exemplo  "BR - Prefeitura de Belo Horizonte", para destacar e ordenar por país.

**Comment by luisfelipebr** [comment]
sugestão adotada. discussão continua em #2
